### ISSUE TITLE
having issue with docker port 

### ISSUE THREAD

**Issue by grandrivers** [scline/docker-cacti#24] opened 2017-09-19 01:52 UTC
says 
/dev/tcp/localhosts/3306: cannot assign requested address

**Comment by scline** [comment] 2017-09-19 18:08
Is this using master or a different branch, what OS are you running this container from so I can try to reproduce.

**Comment by grandrivers** [comment] 2017-09-20 00:40
i am new to docker so could be noob issue
this is on ubuntu 16.04  just did pull from docker hub 
also running some ubiquiti software : unms, unifi, aircontrol 2

**Comment by scline** [comment] 2017-09-21 20:36
Gotcha, this weekend I will try and get some time to reproduce your issue. One thing you will need is a database (or database container) attached for things to work. Take a look at the `docker-compose` folder for some example of this. - https://github.com/scline/docker-cacti/tree/master/docker-compose

**Comment by scline** [comment] 2017-10-14 04:26
Going to close this out, I am not able to reproduce this issue and I am thinking its related to a missing mysql database being defined or available.

**Closed by scline** 2017-10-14 04:26 UTC
